markdown: kramdown
permalink: /:path/:basename
remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "FFX Info on GitHub":
    - "//github.com/Grayfox96/FFX-Info"

# Sort order for navigation links
nav_sort: case_insensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Grayfox96/FFX-Info"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
